/* Edit this file to add artwork, collections, and journal entries. */
const artworks = [
 {id:1,title:'Stillness After Rain',category:'Painting',collection:'Nature & Silence',year:'2026',medium:'Acrylic on canvas',dimensions:'91 × 122 cm',image:'images/artworks/artwork-01.svg',description:'A meditation on the blue hour after a monsoon shower, when the familiar world pauses and begins again.',story:'This painting began as a small field note from a wet garden. Layers of translucent colour hold the feeling of looking through rain.'},
 {id:2,title:'A Place to Return',category:'Abstract',collection:'Fragments of Memory',year:'2025',medium:'Oil and pigment on canvas',dimensions:'76 × 102 cm',image:'images/artworks/artwork-02.svg',description:'A shifting interior built from remembered rooms and half-seen thresholds.',story:'The work grew slowly, through erasure and return, until the architecture could hold its own atmosphere.'},
 {id:3,title:'Mira at Dusk',category:'Portrait',collection:'Human Expressions',year:'2025',medium:'Charcoal and pastel on paper',dimensions:'56 × 76 cm',image:'images/artworks/artwork-03.svg',description:'A quiet portrait where a direct gaze meets the softness of evening.',story:'Made across three sittings, this is less a likeness than a record of shared concentration.'},
 {id:4,title:'Salt Lines',category:'Photography',collection:'Indian Landscapes',year:'2024',medium:'Archival pigment print',dimensions:'61 × 91 cm',image:'images/artworks/artwork-04.svg',description:'A horizon from the salt flats, where land and sky lose their border.',story:'Photographed at noon, when the reflected light makes distance almost impossible to measure.'},
 {id:5,title:'Notes on a Leaf',category:'Sketch',collection:'Nature & Silence',year:'2024',medium:'Ink on handmade paper',dimensions:'30 × 42 cm',image:'images/artworks/artwork-05.svg',description:'A study of growth, decay and the intricate grammar of a single leaf.',story:'One of many daily drawings made during a residency in the foothills.'},
 {id:6,title:'Tender Geometry',category:'Digital Art',collection:'Fragments of Memory',year:'2023',medium:'Digital collage, edition of 10',dimensions:'50 × 70 cm',image:'images/artworks/artwork-06.svg',description:'Fragments of photographs and drawn marks reassembled into a new emotional terrain.',story:'A digital work that asks how an image can remain tactile even when its surface is light.'},
 {id:7,title:'Red Earth Study',category:'Other',collection:'Indian Landscapes',year:'2023',medium:'Earth pigment on linen',dimensions:'45 × 60 cm',image:'images/artworks/artwork-07.svg',description:'A material study made with local clay pigments.',story:'The palette was gathered on a journey through central India.'},
 {id:8,title:'Between Breaths',category:'Painting',collection:'Human Expressions',year:'2022',medium:'Oil on canvas',dimensions:'102 × 76 cm',image:'images/artworks/artwork-08.svg',description:'A figure suspended in a private moment of becoming.',story:'The painting holds the rhythm of breath as an unspoken form of portraiture.'}
];
const collections=[
 {title:'Nature & Silence',description:'Paintings and field studies that follow weather, botanicals and patient forms of looking.',cover:'images/artworks/artwork-01.svg'},
 {title:'Human Expressions',description:'Portraits and figurative works that attend to gesture, presence and intimacy.',cover:'images/artworks/artwork-03.svg'},
 {title:'Fragments of Memory',description:'A visual archive of interiors, thresholds and the beautiful unreliability of recollection.',cover:'images/artworks/artwork-02.svg'},
 {title:'Indian Landscapes',description:'Works shaped by journeys through changing terrain, light and lived geography.',cover:'images/artworks/artwork-04.svg'}
];
const posts=[
 {id:1,title:'Learning to Paint the Weather',date:'12 September 2026',category:'Process',image:'images/journal/journal-01.svg',excerpt:'What a monsoon season taught me about waiting, layering and letting a painting change its mind.',body:'The weather has become one of my most patient teachers. In the studio, I often try to work quickly, to resolve the uncertainty. But rain has another rhythm. It asks for layers, pauses and the courage to let an image remain open.\n\nThese new paintings began as small watercolour notes made between showers. Back in the studio, the marks became slower and more deliberate. I am learning that atmosphere is not something added at the end; it is the accumulation of every decision.'},
 {id:2,title:'The Value of a Daily Drawing',date:'28 August 2026',category:'Studio Notes',image:'images/journal/journal-02.svg',excerpt:'A modest drawing practice has changed the way I look at almost everything.',body:'A daily drawing is not an audition for a finished work. It is a place to notice. Some days it is a plant, a cup, a face on the metro. The smallness of the format gives permission to fail, and in that permission I find surprise.\n\nOver time, these pages become a private map of attention.'},
 {id:3,title:'Notes from the Salt Flats',date:'04 August 2026',category:'Travel',image:'images/journal/journal-03.svg',excerpt:'On horizons, glare and the strange generosity of an empty landscape.',body:'At noon the salt flats make a horizon disappear. The ground returns the sky so completely that the body loses its usual bearings. I made photographs, but mostly I stood still.\n\nThe experience will return in the studio slowly, as it should.'}
];
